### ISSUE TITLE
로그인 기능 중 토큰이 만료 되었을 때 갱신하는 로직 구현 -> 로그인 기능 리팩토링

### ISSUE THREAD

**Issue by thisisdana49** [Team-PATCH/Harmony-iOS#109]
## 🤷‍♂️ Description
- 로그인 기능 뷰와 로직을 리팩토링합니다.
- 역할과 책임에 맞게 코드를 분리하고, 필요 없는 코드는 삭제합니다.

## 🔄 How to reproduce bug
- #135 

## 📸 Screenshots
- 필요한 경우 사진을 남깁니다.

## ✳️Remarks
- 비고란으로 Optional입니다.

**Comment by WaterBean** [comment]
소셜 토큰과 리프레쉬 토큰은 KakaoSDK에서 자체적으로 갱신해 처리해준다고 합니다. 
참고링크) https://developers.kakao.com/docs/latest/ko/kakaologin/common#login-token-info
최초 로그인시에만 토큰 정보를 포함해 서버에 보내도록 로직을 수정하겠습니다.
