### ISSUE TITLE
Color & Font Extensions & Package Dependencies 추가

### ISSUE THREAD

**Issue by thisisdana49** [Team-PATCH/Harmony-iOS#8]
## 🤷‍♂️ Description
- 프로젝트의 일관된 디자인과 기능 구현을 위해 색상 및 폰트 확장과 패키지 종속성을 정의합니다.

## ❗️Requirements
- Color+Extensions/Font+Extensions 정의 및 추가
- 패키지 관리 도구 설정 및 패키지 추가

## ✳️Remarks
- 패키지 변경 시 프로젝트 파일 변화가 있으므로 Push/Pull 시 주의합니다.

**Comment by sion555** [comment]
SPM Dependency - AlamoDynamic 제거가 필요할 것 같습니다..
